[build]
  command = "pnpm install && pnpm build"
  publish = "dist" 

  [build.environment]
    NODE_ENV = "production"
    PRODUCTS_MFE_URL = "https://microfrontend-products.netlify.app"
    CART_MFE_URL     = "https://microfrontend-cart.netlify.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200